services:
  lupasil-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - REACT_URL=${REACT_URL}
      - DATABASE_URL=${DATABASE_URL}
      - BUCKET_NAME=${BUCKET_NAME}
      - BUCKET_REGION=${BUCKET_REGION}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
    volumes:
      - .:/app:delegated
    working_dir: /app
    command: yarn dev
