version: '3.9'

services:
  lupasil-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    environment:
      REACT_URL: ${REACT_URL}
      DATABASE_URL: ${DATABASE_URL}
      BUCKET_NAME: ${BUCKET_NAME}
      BUCKET_REGION: ${BUCKET_REGION}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
    volumes:
      - .:/lupasil-api
      - /lupasil-api/node_modules
    command: yarn dev
