name: Deploy to VPS

on:
  push:
    branches:
      - main  # Altere para o branch que você deseja fazer o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t wcctech/lupasil-api:latest .

    - name: Push Docker image
      run: docker push wcctech/lupasil-api:latest

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ vars.SERVER_IP }}
        username: ${{ vars.SSH_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull wcctech/lupasil-api:latest
          docker-compose down
          docker-compose up -d