name: Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Defina a versão do Node.js que você está utilizando

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run TypeScript build
        run: yarn tsc --noEmit  # Isso verifica se o código TypeScript está correto, sem gerar arquivos .js

      # - name: Run tests (se você tiver testes, pode rodá-los aqui)
      #   run: yarn test

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}  # Você deve adicionar sua chave privada SSH nos secrets do GitHub
          VPS_HOST: ${{ vars.SERVER_IP }}  # O IP ou domínio do seu VPS
          VPS_USER: ${{ vars.SSH_USER }}  # Usuário SSH para acessar seu VPS
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          rsync -avz --exclude node_modules --exclude .git --delete ./ $VPS_USER@$VPS_HOST:/node
          ssh -i private_key.pem $VPS_USER@$VPS_HOST 'cd /node && yarn install --frozen-lockfile && yarn start'
