name: lupasil.com CI
on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: acho Building the app
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: master
      url: ${{vars.URL}}
    needs: build
    steps:
      - name: Repo Checkout
        uses: action/checkout@v1
      - name: Hostiger Deployment
        uses: easingthemes/ssh-deploy@master
        with:
          # TERM: xterm-256color
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "src/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}
