name: lupasil.com CI
on:
  push:
    branches:
      - master

jobs:
  BuildPushImage:
    name: Build/Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Criação do diretório remoto
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "mkdir -p ${{ secrets.TARGET }}"

      - name: Checkout do repositorio
        uses: actions/checkout@v3
      - name: Deploy para hosting
        uses: easingthemes/ssh-deploy@main
        env:
          TERM: xterm-256color
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "src/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.TARGET }}
