name: lupasil.com CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - uses: actions/checkout@v4

      # Criar arquivo .env com repository variables e secrets
      - name: Configurar arquivo .env
        run: |
          echo "PORT=${{ vars.PORT }}" >> .env
          echo "REACT_URL=${{ vars.REACT_URL }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "BUCKET_NAME=${{ vars.BUCKET_NAME }}" >> .env
          echo "BUCKET_REGION=${{ vars.BUCKET_REGION }}" >> .env
          echo "ACCESS_KEY=${{ secrets.ACCESS_KEY }}" >> .env
          echo "SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}" >> .env

      # Validar variáveis de ambiente criadas
      - name: Validar Variáveis de Ambiente
        run: cat .env

      # Executar docker-compose com o comando 'up'
      - name: Run docker-compose
        run: docker-compose --env-file .env up -d
