name: Deploy to VPS

on:
  push:
    branches:
      - main # O deploy será acionado ao fazer push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      # Build do projeto
      - name: Build project
        run: |
          npx tsc

      # Configuração do SSH para conectar ao servidor VPS
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # Copia os arquivos necessários para o servidor VPS
      - name: Copy files to server
        run: |
          rsync -avz --exclude='.git' --exclude='node_modules' \
            --exclude='.github' ./ ${{ vars.SSH_USER }}@${{ vars.SERVER_IP }}:/home/${{ vars.SSH_USER }}/lupasil-api

      # Executa o Docker Compose no servidor VPS para buildar e subir os containers
      - name: Deploy with Docker Compose
        run: |
          ssh ${{ vars.SSH_USER }}@${{ vars.SERVER_IP }} << 'EOF'
          cd /home/${{ vars.SSH_USER }}/lupasil-api
          docker-compose down # Para qualquer container em execução
          docker-compose up --build -d # Reconstrói e sobe os containers
          EOF
